--CREATE DATABASE FPBI_METADATA
GO

USE FPBI_METADATA
GO

-- Check exists table
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[AUDIT_METADATA]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
  DROP TABLE [dbo].[AUDIT_METADATA]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[ETL_METADATA]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
  DROP TABLE [dbo].[ETL_METADATA]
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[ETL_METADATA_DDS]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1)
  DROP TABLE [dbo].[ETL_METADATA_DDS]
GO

-- Table ETL_METADATA
CREATE TABLE [dbo].[ETL_METADATA] (
  [ID] int IDENTITY(1, 1) NOT NULL,
  [TableName] NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  [LSET] DATETIME NULL,
  [CET] DATETIME NULL,
  [Status] NVARCHAR(100) NULL,
  [RecordCount] INT NULL,
)
ON [PRIMARY]
GO

-- Table ETL_METADATA_DDS
CREATE TABLE [dbo].[ETL_METADATA_DDS] (
  [ID] int IDENTITY(1, 1) NOT NULL,
  [TableName] NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  [LSET] DATETIME NULL,
  [CET] DATETIME NULL,
  [Status] NVARCHAR(100) NULL,
  [RecordCount] INT NULL,
)
ON [PRIMARY]
GO

--Table AUDIT_METADATA
CREATE TABLE [dbo].[AUDIT_METADATA] (
  [ID] int IDENTITY(1, 1) NOT NULL,
  [ETL_ID] INT NOT NULL,
  [TableName] NVARCHAR(100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
  [LSET] DATETIME NULL,
  [CET] DATETIME NULL,
  [Status] NVARCHAR(100) NULL,
  [RecordCount] INT NULL,
  [LSET_OLD] DATETIME NULL,
  [CET_OLD] DATETIME NULL,
  [Source] NVARCHAR(100),
)
ON [PRIMARY]
GO

-- Definition for indices : 
ALTER TABLE [dbo].[ETL_METADATA]
ADD CONSTRAINT [PK_ETL_METADATA] 
PRIMARY KEY CLUSTERED ([ID])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[ETL_METADATA_DDS]
ADD CONSTRAINT [PK_ETL_METADATA_DDS] 
PRIMARY KEY CLUSTERED ([ID])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

ALTER TABLE [dbo].[AUDIT_METADATA]
ADD CONSTRAINT [PK_AUDIT_METADATA] 
PRIMARY KEY CLUSTERED ([ID])
WITH (
  PAD_INDEX = OFF,
  IGNORE_DUP_KEY = OFF,
  STATISTICS_NORECOMPUTE = OFF,
  ALLOW_ROW_LOCKS = ON,
  ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

-- CREATE TRIGGER
CREATE TRIGGER INSERT_ETL_METADATA ON [dbo].[ETL_METADATA] AFTER INSERT
AS 
BEGIN
	UPDATE [dbo].[ETL_METADATA]
	SET LSET = GETDATE(), CET = GETDATE()
	WHERE ID IN (SELECT DISTINCT ID FROM inserted)
END
GO

CREATE TRIGGER INSERT_ETL_METADATA_DDS ON [dbo].[ETL_METADATA_DDS] AFTER INSERT
AS 
BEGIN
	UPDATE [dbo].[ETL_METADATA]
	SET LSET = GETDATE(), CET = GETDATE()
	WHERE ID IN (SELECT DISTINCT ID FROM inserted)
END
GO


SET IDENTITY_INSERT [dbo].[ETL_METADATA] ON
SET IDENTITY_INSERT [dbo].[ETL_METADATA_DDS] ON
GO

--Insert below here

SET IDENTITY_INSERT [dbo].[ETL_METADATA] OFF
SET IDENTITY_INSERT [dbo].[ETL_METADATA_DDS] OFF
GO


